### ISSUE TITLE
[boms-api] create an express app

### ISSUE THREAD

**Issue by tanayhub** [tanayhub/boms#10]
@AmanBhanse in order to get a basic overview of how express works. create a basic express app with a route as `/version` which returns version from its `package.json`. Follow:
- [ ] comment on this issue.
- [ ] wait for me to transfer this issue to [repo](https://github.com/tanayhub/boms-api)
- [ ] fork [repo](https://github.com/tanayhub/boms-api) and create express app with the following packages
  - [ ] express ( facilitates routing )
  - [ ] cors ( enables cross-origin access )
  - [ ] morgan ( enables http logging )
 - [ ] create a PR and also mention issue as follows.

**Comment by AmanBhanse** [comment]
"wait for me to transfer this issue to repo" means?
Are you pushing some more changes to codebase?

**Comment by AmanBhanse** [comment]
And i also observed that current project is not node project. So Do i have to init the node?

**Comment by tanayhub** [comment]
closing as github sucks
